config/routes.rb
Rails.application.routes.draw do
  namespace :registration do
    resource :company, only: %i[new create]
    resource :installer, only: :show do
      collection do
        get :download
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/m_company.rb
class MCompany < ApplicationRecord
  has_many :m_credits

  accepts_nested_attributes_for :m_credits

  # TODO: 正規表現のvalidationは共通化する
  validates :name, presence: true, length: { maximum: 255 }
  validates :postal_nummber, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true, length: { maximum: 255 }
  validates :personnel, presence: true, length: { maximum: 255 }
  validates :personnel_department, presence: true, length: { maximum: 255 }
  validates :personnel_position, presence: true, length: { maximum: 255 }
  validates :tel, presence: true, format: { with: /\A\d{10}\z|\A\d{11}\z/ }
  validates :email, presence: true, format: { with: /\A\S+@\S+\.\S+\z/ }
end

app/models/m_credit.rb
class MCredit < ApplicationRecord
  belongs_to :m_company

  before_save :skimming_number

  validates :name, presence: true, length: { maximum: 255 }
  validates :company, presence: true
  validates :number, presence: true
  validates :expire_on, presence: true

  enum company: { visa: 1, master_card: 2, american_express: 3,
                  discover: 4, jcb: 5, diners_club: 6 }

  def skimming_number
    self.number = number[0..3]
  end
end

app/models/m_user.rb
class MUser < ApplicationRecord
  has_many :m_credits

  accepts_nested_attributes_for :m_credits

  validates :name, presence: true, length: { maximum: 255 }
  # TODO: emailのバリデーション追加
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def index; end

  # REVIEW: DownloadsControllerにdownloadアクションがあるのが気持ち悪い
  def download
    filepath = Rails.root.join('public', 'download_test.txt')
    stat = File.stat(filepath)
    send_file(filepath, filename: 'download_test.txt', length: stat.size)
    render
  end
end

app/controllers/installers_controller.rb
class InstallersController < ApplicationController
  def show; end

  def download
    filepath = Rails.root.join 'public', 'download_test.txt'
    stat = File.stat filepath
    send_file filepath, filename: 'download_test.txt', length: stat.size
    render
  end
end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController
  def index; end

  def create
    # @download = Download.new(download_params)
    #
    # respond_to do |format|
    #   if @download.save
    #     format.html { redirect_to @download, notice: 'Download was successfully created.' }
    #     format.json { render :show, status: :created, location: @download }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @download.errors, status: :unprocessable_entity }
    #   end
    # end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @company = MCompany.new
    @company.m_credits.build
  end

  def create
    @company = MCompany.new company_params
    if @company.save
      redirect_to downloads_path
    else
      # REVIEW: もっといい方法があるはず
      pull_expire_on_from_params
      render :index
    end
  end

  private

  def company_params
    params.require(:m_company).permit(
      :name, :email, :tel, :postal_nummber, :address,
      :personnel, :personnel_department, :personnel_position,
      m_credits_attributes: %i[name company number expire_on]
    )
  end

  def pull_expire_on_from_params
    @expire_on = params[:m_company][:m_credits_attributes]['0'][:expire_on]&.to_date
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/downloads/index.html.slim
.form-panel style="padding: 50px; padding-left: 300px;"
  h3 インストーラーダウンロード
  br
  h4 ご利用規約
  br
  div style="width:75%; height:400px; overflow:auto; border: solid 1px; border-radius: 5px; padding: 20px 20px 20px 20px;"
    h4 第１章 ---
    b 　第１条 --------------
    p 　　---------------------------------。
    b 　第２条 --------------
    p 　　-----------------------------------------------------。
    b 　第３条 --------------
    p 　　-----------------。
    br
    h4 第２章 ---
    b 　第１条 --------------
    p 　　-----------------------------------------。
    b 　第２条 --------------
    p 　　----------------------------------------------------。
    b 　第３条 --------------
    p 　　-----------------------------------------。
    b 　第４条 --------------
    p 　　----------------------------------------------------。
    b 　第５条 --------------
    p 　　----------------------------------------------------。
    h4 第３章 ---
    b 　第１条 --------------
    p 　　-----------------------------------------。
    b 　第２条 --------------
    p 　　----------------------------------------------------。
    h4 第４章 ---
    b 　第１条 --------------
    p 　　----------------------------------------------------。
    b 　第２条 --------------
    p 　　-----------------------------------------。
    b 　第３条 --------------
    p 　　--------------------------------。
    h4 第５章 ---
    b 　第１条 --------------
    p 　　----------------------。
    b 　第２条 --------------
    p 　　----------------------------------------------------。
    b 　第３条 --------------
    p 　　-----------------------------------------。
    b 　第４条 --------------
    p 　　-----------------------------------。
  br
  .form-inline
    = check_box_tag :apply, class: 'form-control'
    | 　利用規約に同意する。
  br
  = link_to 'ダウンロード', download_downloads_path, id: 'download', class: 'btn btn-success disabled'

= javascript_include_tag 'downloads'

app/views/installers/show.html.slim
.form-panel style="padding: 50px; padding-left: 300px;"
  h3 インストーラーダウンロード
  br
  h4 ご利用規約
  br
  div style="width:75%; height:400px; overflow:auto; border: solid 1px; border-radius: 5px; padding: 20px 20px 20px 20px;"
    h4 第１章 ---
    b 　第１条 --------------
    p 　　---------------------------------。
    b 　第２条 --------------
    p 　　-----------------------------------------------------。
    b 　第３条 --------------
    p 　　-----------------。
    br
    h4 第２章 ---
    b 　第１条 --------------
    p 　　-----------------------------------------。
    b 　第２条 --------------
    p 　　----------------------------------------------------。
    b 　第３条 --------------
    p 　　-----------------------------------------。
    b 　第４条 --------------
    p 　　----------------------------------------------------。
    b 　第５条 --------------
    p 　　----------------------------------------------------。
    h4 第３章 ---
    b 　第１条 --------------
    p 　　-----------------------------------------。
    b 　第２条 --------------
    p 　　----------------------------------------------------。
    h4 第４章 ---
    b 　第１条 --------------
    p 　　----------------------------------------------------。
    b 　第２条 --------------
    p 　　-----------------------------------------。
    b 　第３条 --------------
    p 　　--------------------------------。
    h4 第５章 ---
    b 　第１条 --------------
    p 　　----------------------。
    b 　第２条 --------------
    p 　　----------------------------------------------------。
    b 　第３条 --------------
    p 　　-----------------------------------------。
    b 　第４条 --------------
    p 　　-----------------------------------。
  br
  .form-inline
    = check_box_tag :apply, class: 'form-control'
    | 　利用規約に同意する。
  br
  = link_to 'ダウンロード', download_installer_path, id: 'download', class: 'btn btn-success disabled'

= javascript_include_tag 'downloads'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Sinnon
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-header style="width: 100%;"
           .navbar-brand style="position:relative; left: 50%;" BATON
    = yield